#!/bin/bash
# SUMMARY: Add a file or stdin to a named ref in the local repo
# HELP: USAGE
#    # Add a blob from a file.
#    dk git add-blob <ref|refname under refs/files> <filename>
#
#    # Add a blob from stdin
#    dk git add-blob <ref|refname under refs/files>
# DESCRIPTION
#    Create a new Git blob from either stdin or a file and point a reference at
#    it.
#    If ref does not have the `refs/files/` prefix, the prefix will be added.
#    If the ref already exists, this command will overwrite it.
#
# LIMITATIONS
#    Since keys are actually refs, the usual restrictions on ref names and ref
#    namespaces apply. In particular, after prepending "refs/files/", ref must
#    satisfy git check-ref-format <ref>, and you cannot have a ref that is a
#    directory prefix of another ref. For example, you can have foo/bar and
#    foo as keys, but both cannot exist simultaneously.

REF_PREFIX=${REF_PREFIX:-refs/files}

if [[ $# -eq 0 ]]; then
  exec dk help git add-blob
fi

# Normalize the ref.
if [[ "$1" = "${REF_PREFIX}"/* ]]; then
  ref="$1"
else
  ref="${REF_PREFIX}/$1"
fi

# Input from stdin
if [[ $# -lt 2 ]] || [[ "$2" = "-" ]]; then
  >&2 echo "Adding stdin to $ref."
  blob_sha="$(git hash-object -w --stdin)"
else # Input from a file
  filename="$2"
  if [[ ! -f "$filename" ]]; then
    >&2 echo "Input '$filename' is not a file!"
    exit 1
  fi

  >&2 echo "Adding $filename to $ref."
  blob_sha="$(git hash-object -w "$filename")"
fi

existing_ref="$(git show-ref "$ref")"
if [[ -n "$existing_ref" ]]; then
  previous_sha="$(echo "$existing_ref" | awk '{print $1}')"
  if [[ "$previous_sha" != "$blob_sha" ]]; then
    >&2 echo "Previous value of $ref was ${previous_sha}."
    git update-ref -d "$ref"
  fi
fi
git update-ref "$ref" "$blob_sha" > /dev/null

# Write to FD 3 if it is open. This is useful for scripts that want to consume
# the information without extra information for humans.
# To consume this ref, a calling script can open FD 3 and direct it to stdout to
# collect the output in a variable.
# REF="$(dk git add-blob file_reference file.txt 3>&1)"
if (printf '' 1>&3) 2>&-; then
  >&3 echo "$ref"
fi
